version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  flask:
    build: .
    container_name: flask
    ports:
      - "8081:5000"
