version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
